---
title: "VUW Psych 423: Culture and Social Behavior"
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: https://orcid.org/0000-0002-5861-2056
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview of assessments

**ALL ASSESSMENTS SHOULD BE SUBMITTED ON BLACKBOARD**

5 x article “peer” review reports of an assigned reading = 25%.

10 x class participation + engagement points = 10%. 

1 x student led presentation = 10%.

1 x Grant application initial proposal = 15% “application inquiry” – or preliminary plan.

1 x Grant application final grant = 40%


**All submissions of work should be on Blackboard.**

### 5 x Peer Review Article Reports: 25% (up to 1000 words each)

The *Peer Review Article Report* will offer you for training in the art of offering constructive, critical feedback to another person or team's ideas.  In developing this art, you'll also develop your abilities for effective communication. 

Due dates (prior to class):

  - ~~FEB 25~~
  - MAR 4
  - MAR 11
  - MAR 18
  - MAR 25
  - APR 1
  - BREAK
  - APR 22
  - APR 29
  - MAY 6
  - MAY 13
  - MAY 20
  - ~~MAY 27~~ (class discussion)


### 1 x Seminar Presentation: 10% (up to 10 minutes)

In which you lead a class discussion by presenting your peer review article report. You will evaluate the strengths and weaknesses of an article, and offer an evaluation of where it fits in with the the larger cultural evolutionary literature.  

Prepare your presentation for one of the following dates

#### Sign up for a presentation:

`Blackboard` $\to$ `Student-led presentation` $\to$ `Presentation sign-up`  for one of the following dates:

  - ~~FEB 25~~
  - MAR 4
  - MAR 11
  - MAR 18
  - MAR 25
  - APR 1
  - BREAK
  - APR 22
  - APR 29
  - MAY 6
  - MAY 13
  - MAY 20
  - ~~MAY 27~~
  - FINAL PROJECT DUE 31 MAY

The presentations should be about 10 minutes long and focussed on one reading. Try to end with a question that will spark conversation. 
  
  
### 10 x Seminar participation reports: 10% (~ 100 words each)

In which you:

1. turn up (.5 pt)
2. offer a brief description of a thought, question, or insight you've had during the seminar ( .5pt)

Note that you can miss 2 x seminars and still receive full points for this assessment. 


Dates: 

  - FEB 27
  - MAR 5
  - MAR 12
  - MAR 19
  - MAR 26
  - APR 2
  - BREAK
  - APR 23
  - APR 29
  - MAY 6
  - MAY 13
  - MAY 20
  - MAY 27




### The Grant Proposal (total = 55%) 

The course culminates with an in-depth project called "The Grant" in which students develop a grant proposal for conducting original research. Effective grant-writing requires a command of the relevant science, concision, clarity, and imagination.

For report templates click [here](https://go-bayes.github.io/psych-423/templatesC.html) for a templates


- One-page "EOI" grant initial proposal due MIDNIGHT APRIL 24 = 15%

- Final grant proposal due MIDNIGHT 31 MAY = 40% 



## Link to templates and marking criteria

For report templates and marking criteria for assessments go  [here](https://go-bayes.github.io/psych-423/templatesC.html) 


###  Appendix 1: The Heilmeier Catechism

  1. What are you trying to do? Articulate your objectives using absolutely no
jargon. What is the problem?  Why is it hard?
  2. How is it done today, and what are the limits of current practice?
  3. What is new in your approach, and why do you think it will be successful?
  4. Who cares?
  5. If you’re successful, what difference will it make? What applications are enabled as a result?
  6. What are the risks?
  7. How much will it cost?
  8. How long will it take?
  9. What are the midterm and final “exams” to check for success? How will progress be measured?

For a bio of George Heilmeier [here](https://ethw.org/George_H._Heilmeier)
See also [here](http://people.physics.illinois.edu/Celia/Heilmeier.pdf)


