---
title: "Templates"
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
date: 2021-FEB-25
output:
  distill::distill_article:
    self_contained: false
    toc: true
    highlight: pygments
    highlight_downlit: false
---

## Submission 

**ALL ASSESSMENTS SHOULD BE SUBMITTED ON BLACKBOARD**


<!-- ## Link to Article Review Template -->

<!-- ### PDF -->
<!-- [Click for PDF](https://www.dropbox.com/s/otxtm6hnq6kep7p/template_review.pdf?dl=0) -->

<!-- ### DOC -->
<!-- [Click for .docx](https://www.dropbox.com/s/187nazd8bkn85fp/template_review.docx?dl=0) -->

<!-- ### RMD -->
<!-- [Click for .Rmd](https://www.dropbox.com/s/20u76gtecn5yn20/template_review.Rmd?dl=0) -->


<!-- ### Asssesment criteria on the seminar participation reports: -->

<!--   - Clarity -- 33.33% -->
<!--   - Creativity -- 33.34% -->
<!--   - Insight -- 33.33% -->

<!-- ### Marking criteria on the seminar participation reports (journals): -->

<!--   - Clarity -- 33.33% -->
<!--   - Creativity -- 33.34% -->
<!--   - Insight -- 33.33% -->

<!-- ## Assessment Criteria for the Article Review  -->

<!-- ### EXCEL -->
<!-- [Click here for Excel Spreadsheet](https://www.dropbox.com/s/ikymfyuiqfdzt64/423_peer_review_marking_templated.xlsx?dl=0) -->


## GRANT PROPOSAL 

<!-- ## Link to the one-page EOI template -->

<!-- [Click here](https://www.dropbox.com/s/37ugg9varpc3b9y/2AB%20EOI.doc?dl=0) -->

<!-- ## Example of a one-page EOI -->
<!-- [Click here](https://www.dropbox.com/s/kacha7gm1tc6xvx/exampleonepager.pdf?dl=0) -->


## Guidelines and Template for Marsden Full Proposal (2013 -- note the headings in Section 2 have changed since 2013)
[Click here](https://www.dropbox.com/s/wb9wfyedtc3m1mh/TEMPLATE_SDSection2.pdf?dl=0)

## Example of a Marsden Full Proposal (2013)
[Click here](https://www.dropbox.com/s/nxfadzqr0gz0z3u/example_long.pdf?dl=0)

## For help with your Vision Mātauranga statement
You may contact our School of Psychology Kaiāwhina Albert-Tibble: 
[Website](https://www.wgtn.ac.nz/psyc/about/staff/albert-tibble)

Email: albert.tibble@vuw.ac.nz
DD:  +64 4 886 4437

## Instructions for the full grant proposal 

(The following instructions are adapted form the Royals Society of New Zealand Marden Grant)

Note that your instructions are exactly those everyone applying for Marden Foundation grant receives.  

I will, however, **bold** key information. 


### Section 1 Summary, Type of Research Activity

These have been carried over from the EOI for reference. However please note that the full proposal summary (**up to 200 words in length**) is different from the shorter summary required in the EOI, both in terms of length and the intended audience. It should summarise the proposed research in straightforward language, but without loss of accuracy or excessive over-simplification. Note that this will be made publicly available should the proposal be successful, and may be published as part of the Marsden Fund’s publicity.

If the summary contains confidential or sensitive material, please indicate this at the summary start: “This summary contains sensitive or confidential information and will be released when the contract is completed”.

As for the EOI, the type of research activity is not accessible to anyone involved in the assessment of the proposals.

### Sections 2a – 2d: Background, Overall Aim, Proposed Research and Vision Mātauranga

**If no Vision Mātauranga theme is identified in Section 3, the total page limit for this section is five pages, with no set limit for each section within this.**

**If one or more Vision Mātauranga theme is identified in Section 3, the total page limit for this section is six pages*** with no set limit for each section within this.
Please read the definitions of these sections clearly, and avoid repetition.

#### Section 2a: Background

Use this section to give a context for the proposal by **summarising in plain language the state of knowledge in the field.**

#### Section 2b: Overall Aim of the Research
Use this section to state **the general goals and specific objectives of the research proposal. Outline the potential for significant scholarly impact of your proposal (incorporating novelty, originality, insight and ambition).**

#### Section 2c: Proposed Research
This section should cover, where appropriate, **the hypotheses being tested,** the **methodology** to be used, sampling design, and methods of data analysis. Please ensure that your description covers the period of funding sought (up to three years), and that it includes contributions by collaborators and postgraduate students (if any).

If you identify one or more Vision Mātauranga themes in Section 3, please elaborate here how this fits in with your proposed research. For example, you may wish to discuss consultations and linkages, relevance, conceptual framework and/or proposal design, and outcomes (in addition to statements in Section 2d).

We are keen to see an increased emphasis on ethical considerations of the proposed research, particularly in the social sciences disciplines.

If the proposed research requires ethics approval, please use this section to show that you have considered all of the ethics issues associated with your research. Your discussion should satisfy the panel that your processes are meaningful, and for social science disciplines in particular, that you have fully considered how your methods will affect the communities you are working with. It is important that you do not concentrate solely on your theoretical argument at the neglect of methodology, implementation, and community safety.

#### Section 2d: Vision Mātauranga

**Please refer to earlier guidelines on Vision Mātauranga.**

If you identify one or more Vision Mātauranga themes in Section 3, please include discussion of this within Section 2d, for example, on consultation and linkages, relevance, conceptual framework and/or proposal design, and outcomes.

Statements on Vision Mātauranga should be contained within Section 2d, following the description of research (Sections 2a-2c). This is to enable Vision Mātauranga to be more easily integrated into the conceptual framework and/or research design. Where Vision Mātauranga is appropriate to a proposal, it can contribute to the overall excellence.

Compliance aspects, such as access to culturally sensitive material and knowledge, should be covered in Section 2h, “Ethical or Regulatory Obligations”.

Aspects of Vision Mātauranga relating to relevant experience can be included in the “Roles and Resources” section (2g) and can also be incorporated into sections 2a-2c.

#### Section 2e: References

References for the Background, Overall Aims, Proposed Research and Vision Mātauranga sections (Sections 2a-d) should be listed here in Section 2e, and should not exceed three pages in length.

#### Section 2f: Timetable

Describe in general terms the advances you hope to make in each year. It is acknowledged that this timetable may be revised as the research progresses.


### Resources: 

Clearly state the resources required for the proposed research that the team will have access to. This is an opportunity to discuss the practical requirements of your proposed research. For example: Access to libraries/collections/archives; access to required instruments/equipment/techniques/materials; ability to do fieldwork (e.g. site access, assistance, etc.); access to pools of participants.

If there are any special requirements for the proposed research, please explain how these will be met.

### Section 2h: Ethical or Regulatory Obligations

Any permissions, approvals, etc., should be listed in this section.

It is your responsibility to ensure that all ethical or regulatory obligations are met (for example, from ERMA, MPI, Animal Ethics, Human Ethics). It is also your responsibility to organise access to facilities, fieldwork sites, archives, materials etc. This section should make clear that you have anticipated or gained the necessary formal approvals for your intended research, for instance, Department of Conservation permits, ERMA permits, and so forth.

Researchers should plan the necessary approvals well in advance, to ensure no delays to the project should it be funded. Researchers should contact their institutional ethics committee and research offices for further information. Researchers will need to provide information on the current state of their ethics approval.

Note that only compliance aspects related to ethical or regulatory considerations should be covered here. Ethical considerations in the context of the research methodology should be discussed in detail in the Proposed Research section (2c), as mentioned previously.

### Social Research

Researchers collecting personal information should be aware of their obligations around obtaining consents, data security, maintaining the anonymity of individuals, sensitivity around cultural issues and all other ethical considerations as appropriate. If there is any uncertainty, researchers should consult their institutional ethics committee.

There is a requirement that any researchers working with children follow the guidelines of their host institution’s child protection policy, in accord with section 19 of the Vulnerable Children’s Act 2014. Should the host institution not have a child protection policy, researchers should comply with the Society’s guidelines:

https://royalsociety.org.nz/who-we-are/our-rules-and-codes/policy-on-child-protection/child-protection-policy/


### Vision Mātauranga (Updated for 2020)

These are the updated guidelines which were included in the 2020 EOI Guidelines. They are also available at https://www.royalsociety.org.nz/what-we-do/funds-and-opportunities/marsden/marsden-fund-application-process/submitting-a-proposal/vision-matauranga/


#### Background

Vision Mātauranga is a policy about innovation, opportunity and the creation of knowledge that highlights the potential contribution of Māori knowledge, resources and people.

https://royalsociety.org.nz/what-we-do/funds-and-opportunities/marsden/application/submitting-a-proposal/vision-matauranga/

http://www.mbie.govt.nz/info-services/science-innovation/agencies-policies-budget-initiatives/vision-matauranga-policy/?searchterm=vision%20matauranga%2A

#### There are four themes:

Indigenous Innovation, which involves contributing to economic growth through distinctive research and development;

Taiao, which is concerned with achieving environmental sustainability through iwi and hapū relationships with land and sea;

Hauora/Oranga, which centres around improving health and social wellbeing; and
Mātauranga, which involves exploring indigenous knowledge.

####  Vision Mātauranga and the Marsden Fund

Please note that Vision Mātauranga is now included as an assessment criterion:

Proposals should consider the relation of the research to the themes of Vision Mātauranga and, where relevant, how the project will engage with Māori.

At the Full Proposal round, up to one additional page will be available for statements on Vision Mātauranga immediately following the description of research in Sections 2a-2c. This is to enable Vision Mātauranga to be more easily integrated into the conceptual framework and/or research design. Where Vision Mātauranga is appropriate to a proposal, it can contribute to the assessment of its overall excellence.

How do I decide whether to include a Vision Mātauranga statement in my proposal?

**A Vision Mātauranga statement must be included for all research that has relevance for Māori.** The research category descriptions outlined in the next section may help you decide if this applies to your project. Please note, however, that those categories are fluid, there may well be overlap between them, and not every point in each category need apply.

#### Categories of Research

The five categories identified below have been adapted from those on the National Science Challenge, Biological Heritage website https://bioheritage.nz/about-us/vision-matauranga/  hosted by Manaaki Whenua Landcare Research. Please note that there may well be overlap between categories as in categories 2 and 3 in terms of the nature and degree of relevance to Māori.

The original categories were set out by MBIE in information for the Endeavour Fund c. 2015.

##### 1.     Research with no specific Māori component
No mātauranga Māori (Māori knowledge) is used.
Māori are not associated with the research process (e.g. not on any research management / advisory / governance panels, it is not inclusive of Māori land or institutions, nor the subject of any component of the research).
Work is not likely to be of greater direct relevance to Māori than members of any other group.
##### 2.     Research specifically relevant to Māori
This category includes research projects where:

There is specific relevance to Māori.
Mātauranga Māori may be used in a minor way to guide the work and its relevance to Māori.
It includes work that contributes to Māori aspirations and outcomes.

##### 3.     Research involving Māori
This category includes research projects where:

Mātauranga Māori may be incorporated in the project, but is not central to the project.
Research is specifically and directly relevant to Māori and Māori are involved in the design and/or undertaking of the research.
The work typically contributes to Māori (e.g., iwi / hapū, organisations) aspirations and outcomes.


##### 4.     Māori-centred research
This category includes research projects where:

The project is Māori led, and where Mātauranga Māori is used alongside other knowledges (e.g. through frameworks, models, methods, tools, etc.).
Kaupapa Māori research is a key focus of the project.
Research is typically collaborative or consultative, with direct input from Māori groups, commonly including Māori researchers or a collaboration with Māori researchers or researchers under the guidance/mentoring of Māori.
There is alignment with and contribution to Māori (e.g., iwi / hapū, organisations) aspirations.

##### 5.     Kaupapa Māori research
This category includes research projects where:

Mātauranga Māori is incorporated, used and understood, as a central focus of project and its findings.

Research is grounded in te ao Māori and connected to Māori philosophies and principles.
Research typically uses kaupapa Māori research methodologies.

Te reo Māori may be a central feature to this kaupapa or research activity, and key researchers have medium to high cultural fluency or knowledge of tikanga and reo.
The research is generally led by a Māori researcher; non-Indigenous researchers may carry out research under the guidance/mentoring of a Māori researcher.
Māori participation (iwi/hapū/marae/individual) is high.
The work contributes strongly to Māori (e.g., iwi/hapū, organisations) aspirations and outcomes and is mana enhancing.

### IV.  Developing a Vision Mātauranga statement

**It is important to keep in mind that there is no single approach or prescription for Vision Mātauranga:** one size does not fit all and there are many possible ways of addressing Vision Mātauranga. Vision Mātauranga should not, however, be seen as an add-on, nor should it be treated as separate from the research, methods or people involved in the project. A holistic approach that considers reciprocity and relationships is therefore desirable.

Vision Mātauranga does not begin and end with your Vision Mātauranga statement. You should document how you have considered Vision Mātauranga and demonstrate applicable actions and relationships throughout the research. The following questions may be useful to consider when conceptualising and writing your project:

Have you co-created the research topic/issue with an iwi or Māori organisation?
What does working in partnership with iwi mean to you as researchers?

To what extent have you discussed the research with Māori partners and agreed on the methodology you will use?

Was there full disclosure and informed consent to the proposed research with Māori partners? How has that agreement/informed consent been agreed to?

Has budget been disclosed and agreed to with Māori partners? 

Is there provision in that budget for Māori involvement, capability development and consultation?

Is there appropriate Māori researcher involvement in the project, both in terms of PI/AIs and capability development?

What provisions have you made to ensure there is advice from appropriate Māori organisations throughout the life of the research project? 

If there are concerns or disagreements with Māori partners, how are these to be resolved?

What provisions have you made to ensure there is appropriate technology transfer to Māori partners as the research proceeds and as findings become available towards the end of the project?

Are there benefits to Māori? What are they? And how have these been agreed with Māori partners?

How is the project an opportunity to build the capacity of Māori researchers or students in your discipline?

How will you share the research outcomes with Māori?

Has there been agreement about the intellectual property ownership of research findings with Māori partners? 

What is the nature of that agreement?

Is there a need for members of the research team to be proficient in te reo? How has this aspect been addressed?

Is there a Tiriti o Waitangi component or requirement in your research?

Is the research mana enhancing?

### V.                Vision Mātauranga Resources

Below you will find a non-exhaustive list of published resources that describe, discuss, and talk about how researchers have engaged with Vision Mātauranga and kaupapa Māori research. These range from early conceptions of Vision Mātauranga to more recent frameworks. The resources underscore the diverse ways Vision Mātauranga may be approached across disciplines and methodologies.

Allen, W., Jamie M. Ataria, J. M., Apgar, J. M., Harmsworth, G., and Tremblay, L. A. (2009). Kia pono te mahi putaiao—doing science in the right spirit. Journal of the Royal Society of New Zealand, 39:4, 239-242.
DOI: 10.1080/03014220909510588

Crawford, S. (2009). Matauranga Maori and western science: The importance of hypotheses, predictions and protocols, Journal of the Royal Society of New Zealand, 39:4, 163-166. 
DOI: 10.1080/03014220909510571

Broughton, D. (Te Aitanga-a-Hauiti, Taranaki, Ngāti Porou, Ngāpuhi), and McBreen, K. (Waitaha, Kāti Māmoe, Ngāi Tahu). (2015). Mātauranga Māori, tino rangatiratanga and the future of New Zealand science. Journal of the Royal Society of New Zealand, 45:2, 83-88.
DOI: 10.1080/03036758.2015.1011171

Kana, F. and Tamatea, K. (2006). Sharing, listening, learning and developing understandings of Kaupapa Māori research by engaging with two Māori communities involved in education. Waikato Journal of Education, 12, 9-20. https://researchcommons.waikato.ac.nz/bitstream/handle/10289/6198/Kana%20Sharing.pdf?sequence=3&isAllowed=y

Macfarlane, S., Macfarlane, A. and Gillon, G. (2015) Sharing the food baskets of knowledge: Creating space for a blending of streams. In A. Macfarlane, S. Macfarlane, M. Webber, (eds.), Sociocultural realities: Exploring new horizons. Christchurch: Canterbury University Press, 52-67.

Moewaka Barnes, H. (2006). Transforming Science: How our Structures Limit Innovation. Social Policy Journal of New Zealand Te Puna Whakaaro, 29, 1-16. https://www.msd.govt.nz/documents/about-msd-and-our-work/publications-resources/journals-and-magazines/social-policy-journal/spj29/29-pages-1-16.pdf

Pihama, L., Tiakiwai, S.-J., and Southey, K. (eds.). (2015). Kaupapa rangahau: A reader. A collection of readings from the Kaupapa Rangahau workshops series. (2nd ed.). Hamilton, New Zealand: Te Kotahi Research Institute. https://researchcommons.waikato.ac.nz/bitstream/handle/10289/11738/Kaupapa%20Rangahau%20-%20A%20Reader_2nd%20Edition.pdf?sequence=7&isAllowed=y

Smith, L. T., Maxwell, T. K., Puke, H., and Temara, P. (2016). Indigenous knowledge, methodology and mayhem: What is the role of methodology in producing indigenous insights? A discussion from Mātauranga Māori. Knowledge Cultures, 4(3), 131–156.



## Criteria for evaluating the EOI and long grant proposals

(Adapted from the RSNZ Marsden)

Proposal must be on a topic in the cultuaral psychology

Proposals must use an interdisciplinary approach to significantly expand research possibilities and ambition through new researcher and institutional links.

Proposals must have the potential for significant scholarly impact because of the proposal’s novelty, originality, insight and ambition. Scholarly impact is a demonstrable contribution to shifting understanding and advancing methods, theory and application across and within disciplines.

Proposals must be rigorous, and should have a basis in prior research and use a sound research method.

Where relevant to the proposal:
* Proposals should consider the relation of the research to the themes of Vision Mātauranga and, where relevant, how the project will engage with Māori.





