---
title: "Introduction"
subtitle: "Course essentials"
author: "Joseph Bulbulia, Victoria University"
date: "2021-24-02"
output: 
  ioslides_presentation:
    incremental: true
    transition: 0
    smaller: true
---

```{r setup, include=FALSE}
# Packages
library(scales)
library(here)
library(knitr)
library(kableExtra)
library(ggdist)
library(bayesplot)
library(tidyverse)
# knitr chunk options
opts_chunk$set(
  echo = FALSE, 
  cache = TRUE,
  message = FALSE,
  warning = FALSE,
  dev = "svg",
  fig.align = 'center'
  )
# Bayesplot color theme
color_scheme_set("darkgray")
```


## What is culture?

We define culture in a broadly to socially transmitted and acquired information information that affects and enables human cognition and behavior. That's not perfect. For example, its clear that birds, chimps, and other organisms have culture, however, this definition makes a start. 

## What is evolution? 

  1. Variation within a population
  2. Competition among variants 
  3. Inheritance such that there is a faithful transmission to "children" of "parental" traits.
  

## Why combine culture and evolution? 


  1. to clarify otherwise bewildering cultural diversity;
  2. to unlock wisdom in culturally inherited systems;
  3. to  avoid to cultural evolved inequality.   

## What will I be doing in this course? 

Expectations:

  1. Seminars x 12.
  2. Lead 1 x seminar
  3. 4 x peer review reports (see assessments)
  4. 1 x "grant proposal"  (see assessments) 

## How will this course benefit me? 

  1. Knowledge of theory and research
  2. Presentation skills
  3. Effective review writing
  4. Research design and grant-writing.
  
## Help

joseph.bulbulia@vuw.ac.nz
