---
title: "Template for Article Review"
description: |
  Use this template as a guide for writing your article reviews
author:
  - name: Joseph Bulbulia
    url: https://josephbulbulia.netlify.app
    affiliation: Victoria University of Wellington
    affiliation_url: https://www.wgtn.ac.nz
    orcid_id: 0000-0002-5861-2056
date: 2021-FEB-14
bibliography: bibliography.bib
output:
  distill::distill_article:
    self_contained: false
    toc: true
---

## Article summary

A brief lay summary of the article:

  - What question to the author ask? 
  - Is this question important? (If yes, briefly, explain why?)
  - Is this question appropriate for the journal's audience?

##  Methods

  - How to the authors collect evidence to address their question? 
  - Have the data and analysis been included? 
  - If not, have the authors indicated why the data and analysis have not been included.
  - How have the data been analysed? 
  - What are the strengths of their methods? 
  - What are the limitations of their methods?
  - To the authors accurately describe the strengths and limitations of their methods? 


## Results

  - What do the authors claim to find? 
  - Do the authors methods support their findings? 
  - What improvements might be made to the methods to strengthen the authors findings? 
  - (note: please read all supplemental files)


## Conclusions

  - What do the author's infer from their results? 
  - Is the inference supported by their results? 
  - Is the inference interesting? 
  - Have the author's accurately linked their findings to previous research? 
  - Have the author's described future work that might follow from their study? 
  - How might the authors improve their inference? 

## Decision 

  - Should the article be published in its current form? 
  - If not, list revisions that would make the article suitable for publication?
    - Major revisions
    - Minor revisions
  - If the article is not suitable for publication in this journal, what constructive advice might you offer the authors. 
  


See [@bulbulia2016standards].

